version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
    overwrite: true
hooks:
  ApplicationStop:
    - location: scripts/deregister_from_elb.sh
  AfterInstall:
    - location: scripts/restart.sh
      runas: root
  ValidateService:
    - location: scripts/register_with_elb.sh